Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnTheBlog.Data;
using OnTheBlog.Models;
using OnTheBlog.Services.Interfaces;

namespace OnTheBlog.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IImageService _imageService;

        public CategoriesController(ApplicationDbContext context, IImageService imageService)
        {
            _context = context;
            _imageService = imageService;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
              return _context.Categories != null ? 
                          View(await _context.Categories.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Categories'  is null.");
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,ImageFile")] Category category)
        {
            if (ModelState.IsValid)
            {
                if (category.ImageFile != null)
                {
                    category.ImageData = await _imageService.ConvertFileToByteArrayAsync(category.ImageFile);
                    category.ImageType = category.ImageFile.ContentType;
                }
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,ImageData,ImageType,ImageFile")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (category.ImageFile != null)
                    {
                        category.ImageData = await _imageService.ConvertFileToByteArrayAsync(category.ImageFile);
                        category.ImageType = category.ImageFile.ContentType;
                    }

                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Categories'  is null.");
            }
            var category = await _context.Categories.FindAsync(id);

            if (category == null)
            {
                return NotFound();
            }

            foreach (BlogPost? blogPost in category.BlogPosts)
            {
                blogPost.Category = null;
            }

            _context.Categories.Remove(category);
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
          return (_context.Categories?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnTheBlog.Data;
using OnTheBlog.Models;
using OnTheBlog.Services;
using OnTheBlog.Services.Interfaces;

namespace OnTheBlog.Controllers
{
    [Authorize]
    public class CommentsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<BlogUser> _userManager;


        public CommentsController(ApplicationDbContext context, UserManager<BlogUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Comments
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Comments.Include(c => c.Author).Include(c => c.BlogPost);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Comments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Comments == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments
                .Include(c => c.Author)
                .Include(c => c.BlogPost)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // GET: Comments/Create
        public IActionResult Create()
        {
            ViewData["AuthorId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["BlogPostId"] = new SelectList(_context.BlogPosts, "Id", "Title");
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Body,BlogPostId")] Comment comment, string? slug)
        {
            ModelState.Remove("AuthorId");

            if (ModelState.IsValid)
            {
                comment.AuthorId = _userManager.GetUserId(User);
                comment.Created = DateTime.Now;

                // Remove CKEditor <p></p> tags
                comment.Body = Regex.Replace(comment.Body!, @"<[^>]*>", string.Empty);

                _context.Add(comment);
                await _context.SaveChangesAsync();

                return RedirectToAction("Details", "BlogPosts", new { slug = slug});
            }

            return View(comment);
        }

        // GET: Comments/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Comments == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments.FindAsync(id);
            if (comment == null)
            {
                return NotFound();
            }
            ViewData["AuthorId"] = new SelectList(_context.Users, "Id", "Id", comment.AuthorId);
            ViewData["BlogPostId"] = new SelectList(_context.BlogPosts, "Id", "Content", comment.BlogPostId);
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Created,Updated,UpdateReason,Body,AuthorId,BlogPostId")] Comment comment)
        {
            if (id != comment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(comment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommentExists(comment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Users, "Id", "Id", comment.AuthorId);
            ViewData["BlogPostId"] = new SelectList(_context.BlogPosts, "Id", "Content", comment.BlogPostId);
            return View(comment);
        }

        // GET: Comments/Delete/5
        [Authorize(Roles = "Admin,Moderator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Comments == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments
                .Include(c => c.Author)
                .Include(c => c.BlogPost)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // POST: Comments/Delete/5
        [Authorize(Roles = "Admin,Moderator")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Comments == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Comments'  is null.");
            }
            var comment = await _context.Comments.FindAsync(id);

            if (comment == null)
            {
                return NotFound();
            }

            BlogPost? blogPost = await _context.BlogPosts
                                            .Where(b => b.Id == comment.BlogPostId)
                                            .FirstOrDefaultAsync();

            if (blogPost == null)
            {
                return NotFound();
            }

            string? slug = blogPost.Slug;

            if (comment != null)
            {
                _context.Comments.Remove(comment);
            }
            
            await _context.SaveChangesAsync();

            return RedirectToAction("Details", "BlogPosts", new { slug });


        }

        private bool CommentExists(int id)
        {
            return (_context.Comments?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnTheBlog.Data;
using OnTheBlog.Models;

namespace OnTheBlog.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TagsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TagsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Tags
        public async Task<IActionResult> Index()
        {
              return _context.Tags != null ? 
                          View(await _context.Tags.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Tags'  is null.");
        }

        // GET: Tags/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Tags == null)
            {
                return NotFound();
            }

            var tag = await _context.Tags
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tag == null)
            {
                return NotFound();
            }

            return View(tag);
        }

        // GET: Tags/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tags/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tag);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        // GET: Tags/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Tags == null)
            {
                return NotFound();
            }

            var tag = await _context.Tags.FindAsync(id);
            if (tag == null)
            {
                return NotFound();
            }
            return View(tag);
        }

        // POST: Tags/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Tag tag)
        {
            if (id != tag.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tag);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TagExists(tag.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        // GET: Tags/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Tags == null)
            {
                return NotFound();
            }

            var tag = await _context.Tags
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tag == null)
            {
                return NotFound();
            }

            return View(tag);
        }

        // POST: Tags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Tags == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Tags'  is null.");
            }
            var tag = await _context.Tags.FindAsync(id);
            if (tag != null)
            {
                _context.Tags.Remove(tag);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TagExists(int id)
        {
          return (_context.Tags?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_AuthorAreaPartial.cshtml
@inject IImageService _imageService
@{
    bool showCode = ViewData["ShowCode"] as bool? ?? false;
}
<div class="axil-author-area axil-author-banner bg-color-grey">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="about-author">
                    <div class="media">

                        @if (User.IsInRole("Admin") && (showCode == true))
                        {
                            <div class="author-info">
                                <h1 class="title p-3"><span>Admin Area</span></h1>
                            </div>
                            <div class="media-body d-flex flex-column align-items-center">
                                @if (Model.IsPublished == false)
                                {
                                    <a class="w-75 btn btn-outline-success"
                                       asp-action="Publish" asp-controller="BlogPosts" asp-route-id="@Model.Id" asp-route-sourceView="Details">Publish</a>
                                }
                                else
                                {
                                    <a class="w-75 btn btn-outline-success"
                                       asp-action="Unpublish" asp-controller="BlogPosts" asp-route-id="@Model.Id" asp-route-sourceView="Details">Unpublish</a>
                                }
                                <a class="w-75 btn btn-outline-warning"
                                   asp-action="Edit" asp-controller="BlogPosts" asp-route-id="@Model.Id" asp-route-sourceView="Details">Edit </a>
                                @if (Model.IsDeleted == false)
                                {
                                    <a class="w-75 btn btn-outline-danger"
                                       asp-action="Delete" asp-controller="BlogPosts" asp-route-id="@Model.Id" asp-route-sourceView="Details">Delete</a>
                                }
                                else
                                {
                                    <a class="w-75 btn btn-outline-danger"
                                       asp-action="Undelete" asp-controller="BlogPosts" asp-route-id="@Model.Id" asp-route-sourceView="Details">Undelete</a>
                                }
                            </div>

                        }
                        else
                        {
                            <div class="row">
                                <div class="thumbnail m-2 col col-12 col-md-4 text-center">
                                    <a>
                                        <img src="~/img/headshot.png" alt="Author Images" class="author_image">
                                    </a>
                                </div>
                                <div class="media-body col col-12 col-md-8">
                                    <div class="author-info">
                                        <h1 class="title text-center">Glenn Schwartz</h1>
                                        <span class="b3 subtitle text-center">Software Developer</span>
                                    </div>
                                    <div class="content">
                                        <p class="b1 description">Here you will find posts I wrote detailing the steps I've taken as a web developer to learn and create new things. All in a blog platform put together by me!</p>
                                        <ul class="social-share-transparent size-md">
                                            <li><a href="https://github.com/Relliumachine42"><i class="fab fa-github"></i></a></li>
                                            <li><a href="mailto:glennschwartz42@gmail.com"><i class="far fa-envelope"></i></a></li>
                                            <li><a href="https://www.linkedin.com/in/glenn-schwartz/"><i class="fab fa-linkedin-in"></i></a></li>
                                            <li><a href="https://schwartz-portfolio.netlify.app/"><i class="fas fa-link"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Shared/_BlogCardPartial.cshtml
@model BlogPost
@inject IImageService _ImageService

<div class="content-block post-list-view mt--30">
    <div class="post-thumbnail">
        <a asp-action="Details" asp-controller="BlogPosts" asp-route-slug="@Model?.Slug">
            <img src="@_ImageService.ConvertByteArrayToFile(Model?.ImageData,Model?.ImageType,DefaultImage.BlogPostImage)" alt="Post Images">
        </a>
    </div>
    <div class="post-content">
        <div class="post-cat">
            <div class="post-cat-list">
                <a class="hover-flip-item-wrapper" asp-action="CategoryFilter" asp-controller="BlogPosts" asp-route-category="@Model?.Category?.Name">
                    <span class="hover-flip-item">
                        <span data-text="@Model?.Category?.Name">@Model?.Category?.Name</span>
                    </span>
                </a>
            </div>
        </div>
        <h4 class="title">
            <a asp-action="Details" asp-controller="BlogPosts" asp-route-slug="@Model?.Slug">
                @Model?.Title
            </a>
        </h4>
        <div class="post-meta-wrapper">
            <div class="post-meta">
                <div class="content">
                    <h6 class="text-truncate d-inline-block" style="max-width: 350px;">
                        @Model?.Abstract       
                    </h6>
                    <ul class="post-meta-list">
                        <li>@Model?.Created.ToString("MMM dd, yyyy")</li>
                        <li>@Model?.Comments.Count Comments</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Shared/_InstaPartial.cshtml
<div class="axil-instagram-area axil-section-gap bg-color-grey">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <h2 class="title">Instagram</h2>
                </div>
            </div>
        </div>
        <div class="row mt--30">
            <div class="col-lg-12">
                <ul class="instagram-post-list">
                    <li class="single-post">
                        <a href="#">
                            <img src="assets/images/small-images/instagram-md-01.jpg" alt="Instagram Images">
                            <span class="instagram-button"><i class="fab fa-instagram"></i></span>
                        </a>
                    </li>
                    <li class="single-post">
                        <a href="#">
                            <img src="assets/images/small-images/instagram-md-02.jpg" alt="Instagram Images">
                            <span class="instagram-button"><i class="fab fa-instagram"></i></span>
                        </a>
                    </li>
                    <li class="single-post">
                        <a href="#">
                            <img src="assets/images/small-images/instagram-md-03.jpg" alt="Instagram Images">
                            <span class="instagram-button"><i class="fab fa-instagram"></i></span>
                        </a>
                    </li>
                    <li class="single-post">
                        <a href="#">
                            <img src="assets/images/small-images/instagram-md-04.jpg" alt="Instagram Images">
                            <span class="instagram-button"><i class="fab fa-instagram"></i></span>
                        </a>
                    </li>
                    <li class="single-post">
                        <a href="#">
                            <img src="assets/images/small-images/instagram-md-05.jpg" alt="Instagram Images">
                            <span class="instagram-button"><i class="fab fa-instagram"></i></span>
                        </a>
                    </li>
                    <li class="single-post">
                        <a href="#">
                            <img src="assets/images/small-images/instagram-md-06.jpg" alt="Instagram Images">
                            <span class="instagram-button"><i class="fab fa-instagram"></i></span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnTheBlog</title>

    <!--BootStrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  
    <link rel="stylesheet" href="~/assets/css/vendor/font-awesome.css">
    <link rel="stylesheet" href="~/assets/css/vendor/slick.css">
    <link rel="stylesheet" href="~/assets/css/vendor/slick-theme.css">
    <link rel="stylesheet" href="~/assets/css/vendor/base.css">
    <link rel="stylesheet" href="~/assets/css/plugins/plugins.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
    <link rel="stylesheet" href="~/css/site.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnTheBlog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BlogPosts" asp-action="Index">Let's See It</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Comments" asp-action="Index">Comments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tags" asp-action="Index">Tags</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OnTheBlog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!-- JS
    ============================================ -->
    <!-- Modernizer JS -->
    <script src="~/assets/js/vendor/modernizr.min.js"></script>
    <!-- jQuery JS -->
    <script src="~/assets/js/vendor/jquery.js"></script>
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="~/assets/js/vendor/slick.min.js"></script>
    <script src="~/assets/js/vendor/tweenmax.min.js"></script>
    <script src="~/assets/js/vendor/js.cookie.js"></script>
    <script src="~/assets/js/vendor/jquery.style.switcher.js"></script>
    <script src="https://kit.fontawesome.com/5f740f3843.js" crossorigin="anonymous"></script>
    <!-- Main JS -->
    <script src="~/assets/js/main.js"></script>
    <script>
        $(function () {
            const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
            const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
        });
    </script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LogoutPartial.cshtml
<form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "BlogPosts", new { area = "" })">
</form>