Models/BlogPost.cs
using Microsoft.EntityFrameworkCore;
using Org.BouncyCastle.Crypto.Paddings;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Reflection.Metadata.Ecma335;
using System.Text.Json.Serialization;

namespace OnTheBlog.Models
{
    public class BlogPost
    {
        private DateTime _created;
        private DateTime? _updated;

        // primary key
        public int Id { get; set; }

        [Required]
        [StringLength(200, ErrorMessage = "The {0} must be at least {2} and max {1} characters long.", MinimumLength = 2)]
        public string? Title { get; set; }

        [StringLength(600, ErrorMessage = "The {0} must be at most {1} characters long.")]
        public string? Abstract { get; set; }

        [Required]
        public string? Content { get; set; }

        public DateTime Created
        {
            get { return _created; }
            set { _created = value.ToUniversalTime(); }
        }

        public DateTime? Updated
        {
            get => _updated;
            set
            {
                if (value.HasValue)
                {
                    _updated = value.Value.ToUniversalTime();
                }
                else
                {
                    _updated = null;
                }
            }
        }

        [Required]
        public string? Slug { get; set; } // "an-interesting-blog-post"

        [Display(Name = "Published?")]
        public bool IsPublished { get; set; }

        [Display(Name = "Deleted?")]
        public bool IsDeleted { get; set; }

        [NotMapped]
        public IFormFile? ImageFile { get; set; }
        public byte[]? ImageData { get; set; }
        public string? ImageType { get; set; }

        //Navigation properties
        public int CategoryId { get; set; }

        [JsonIgnore]
        public virtual Category? Category { get; set; }
        [JsonIgnore]
        public virtual ICollection<Comment> Comments { get; set; } = new HashSet<Comment>();
        [JsonIgnore]
        public virtual ICollection<Tag> Tags { get; set; } = new HashSet<Tag>();
        [JsonIgnore]
        public virtual ICollection<BlogLike> Likes { get; set; } = new HashSet<BlogLike>();

    }
}

Controllers/API/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnTheBlog.Data;
using OnTheBlog.Models;
using OnTheBlog.Services.Interfaces;

namespace OnTheBlog.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class BlogPostsController : ControllerBase
    {
        private readonly IBlogService _blogService;
        public BlogPostsController(IBlogService blogService)
        {
            _blogService = blogService;
        }

        /// <summary>
        /// This endpoint will return the most recently published blog posts.
        /// The count parameter indicates the number of recent posts to return.
        /// The maximum number of blog posts allowed per request is ten.
        /// </summary>
        /// <param name="count">The number of blog posts to retrieve</param>
        /// <returns></returns>
        [HttpGet("{count:int}")]
        public async Task<ActionResult<IEnumerable<BlogPost>>> GetBlogPosts(int count)
        {
            if (count > 10)
            {
                count = 10;
            }

            IEnumerable<BlogPost> blogPosts = (await _blogService.GetBlogPostsAsync()).Take(count);

            return Ok(blogPosts);
        }

    }
}

Controllers/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnTheBlog.Data;
using OnTheBlog.Helpers;
using OnTheBlog.Models;
using OnTheBlog.Services.Interfaces;
using X.PagedList;

namespace OnTheBlog.Controllers
{
    public class BlogPostsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IImageService _imageService;
        private readonly IBlogService _blogService;

        public BlogPostsController(ApplicationDbContext context,
                                      IImageService imageService,
                                      IBlogService blogService)
        {
            _context = context;
            _imageService = imageService;
            _blogService = blogService;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AuthorArea(int? pageNum)
        {
            int pageSize = 3;
            int page = pageNum ?? 1;

            IPagedList<BlogPost> blogPosts = await (await _blogService.GetAllBlogPostsAsync())
                                                                        .Where(b => b.IsPublished == true && b.IsDeleted == false)
                                                                        .ToPagedListAsync(page, pageSize);

            return View(blogPosts);
        }

        // GET: BlogPosts
        [AllowAnonymous]
        public async Task<IActionResult> Index(int? pageNum)
        {
            int pageSize = 3;
            int page = pageNum ?? 1;

            IPagedList<BlogPost> blogPosts = await (await _blogService.GetBlogPostsAsync()).ToPagedListAsync(page, pageSize);

            ViewData["ActionName"] = nameof(Index);

            return View(blogPosts);
        }

        public async Task<IActionResult> SearchIndex(string? searchString, int? pageNum)
        {
            int pageSize = 3;
            int page = pageNum ?? 1;

            IPagedList<BlogPost> blogPosts = await _blogService.SearchBlogPosts(searchString).ToPagedListAsync(page, pageSize);

            ViewData["ActionName"] = nameof(SearchIndex);
            ViewData["SearchString"] = searchString;

            return View(nameof(Index), blogPosts);
        }

        public async Task<IActionResult> CategoryFilter(string? category, int? pageNum)
        {
            int pageSize = 3;
            int page = pageNum ?? 1;

            IPagedList<BlogPost> blogPosts = await _blogService.GetBlogPostsByCategory(category).ToPagedListAsync(page, pageSize);

            ViewData["ActionName"] = nameof(CategoryFilter);
            ViewData["CategoryString"] = category;

            return View(nameof(Index), blogPosts);
        }

        public async Task<IActionResult> BlogFilter(string? filter, int? pageNum)
        {
            int pageSize = 3;
            int page = pageNum ?? 1;

            IPagedList<BlogPost> blogPosts = await _blogService.GetBlogPostsByFilter(filter).ToPagedListAsync(page, pageSize);

            ViewData["ActionName"] = nameof(BlogFilter);
            ViewData["FilterString"] = filter;

            return View(nameof(AuthorArea), blogPosts);
        }
        public async Task<IActionResult> TagFilter(string? tag, int? pageNum)
        {
            int pageSize = 3;
            int page = pageNum ?? 1;

            IPagedList<BlogPost> blogPosts = await (await _blogService.GetBlogPostsByTagAsync(tag)).ToPagedListAsync(page, pageSize);

            ViewData["ActionName"] = nameof(TagFilter);
            ViewData["TagString"] = tag;

            return View(nameof(Index), blogPosts);
        }
        public async Task<IActionResult> Popular(int? pageNum)
        {
            if (_context.BlogPosts == null)
            {
                return NotFound();
            }

            int pageSize = 3;
            int page = pageNum ?? 1;

            IPagedList<BlogPost> blogPosts = await (await _blogService.GetPopularBlogPostsAsync()).ToPagedListAsync(page, pageSize);

            ViewData["ActionName"] = nameof(Popular);

            return View(nameof(Index), blogPosts);
        }

        // GET: BlogPosts/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(string? slug)
        {
            if (string.IsNullOrEmpty(slug))
            {
                return NotFound();
            }

            BlogPost? blogPost = await _blogService.GetBlogPostAsync(slug);

            if (blogPost == null)
            {
                return NotFound();
            }

            ViewData["Slug"] = slug;

            return View(blogPost);
        }

        // GET: BlogPosts/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            return View();
        }

        // POST: BlogPosts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Abstract,Content,IsPublished,CategoryId,ImageFile")] BlogPost blogPost, string? stringTags)
        {

            ModelState.Remove("Slug");

            if (ModelState.IsValid)
            {
                string? newSlug = StringHelper.BlogPostSlug(blogPost.Title);

                if (!await _blogService.ValidSlugAsync(newSlug, blogPost.Id))
                {
                    ModelState.AddModelError("Title", "A similar Title/Slug is already in use.");

                    ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
                    return View(blogPost);
                }

                blogPost.Slug = newSlug;
                blogPost.Created = DateTime.Now;

                if (blogPost.ImageFile != null)
                {
                    blogPost.ImageData = await _imageService.ConvertFileToByteArrayAsync(blogPost.ImageFile);
                    blogPost.ImageType = blogPost.ImageFile.ContentType;
                }

                // use the blog service
                await _blogService.AddBlogPostAsync(blogPost);

                if (string.IsNullOrEmpty(stringTags) == false)
                {
                    IEnumerable<string> tags = stringTags.Split(',');
                    await _blogService.AddTagsToBlogPostAsync(tags, blogPost.Id);
                }

                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", blogPost.CategoryId);
            return View(blogPost);
        }

        // GET: BlogPosts/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.BlogPosts == null)
            {
                return NotFound();
            }

            var blogPost = await _context.BlogPosts.FindAsync(id);
            if (blogPost == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", blogPost.CategoryId);
            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Abstract,Content,Created,Slug,IsPublished,IsDeleted,ImageData,ImageType,CategoryId,ImageFile")] BlogPost blogPost, string? stringTags)
        {
            if (id != blogPost.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string? newSlug = StringHelper.BlogPostSlug(blogPost.Title);

                    if (newSlug != blogPost.Slug)
                    {

                        if (!await _blogService.ValidSlugAsync(newSlug, blogPost.Id))
                        {
                            ModelState.AddModelError("Title", "A similar Title/Slug is already in use.");

                            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
                            return View(blogPost);
                        }

                        blogPost.Slug = newSlug;

                    }

                    blogPost.Created = DateTime.Now;

                    if (blogPost.ImageFile != null)
                    {
                        blogPost.ImageData = await _imageService.ConvertFileToByteArrayAsync(blogPost.ImageFile);
                        blogPost.ImageType = blogPost.ImageFile.ContentType;
                    }

                    await _blogService.UpdateBlogPostAsync(blogPost);

                    if (string.IsNullOrEmpty(stringTags) == false)
                    {
                        IEnumerable<string> tags = stringTags.Split(',');
                        await _blogService.AddTagsToBlogPostAsync(tags, blogPost.Id);
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogPostExists(blogPost.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

Views/BlogPosts/AuthorArea.cshtml
@using X.PagedList.Web.Common;
@model IPagedList<BlogPost>
@inject IImageService _ImageService
@{
    ViewData["Title"] = "AuthorArea";
    string? actionName = ViewBag.ActionName;
    string? filter = "";
    string pageTitle = "";

    switch (actionName)
    {
        case "AuthorArea":
            pageTitle = "My Blogs";
            filter = "";
            break;
        case "Drafts":
            pageTitle = "My Drafts";
            filter = "Drafts";
            break;
        case "Deleted":
            pageTitle = "My Archive";
            filter = "Deleted";
            break;
    }
}

<!-- Start Post List Wrapper  -->
<div class="axil-post-list-area axil-section-gap bg-color-white">
    <div class="container">
        <div class="d-flex">
            <a class="mx-3 axil-button button-rounded btn btn-success mb-5" asp-action="Create" asp-controller="BlogPosts">New Blog Post</a>
            @if (ViewBag.CategoryString == "Drafts")
            {
                <a class="mx-3 axil-button button-rounded btn btn-success mb-5" asp-action="AuthorArea" asp-controller="BlogPosts">Author Area</a>
                <a class="mx-3 axil-button button-rounded btn btn-success mb-5" asp-action="BlogFilter" asp-controller="BlogPosts" asp-route-filter="Deleted">Deleted</a>

            }
            else if (ViewBag.CategoryString == "Deleted")
            {
                <a class="mx-3 axil-button button-rounded btn btn-success mb-5" asp-action="AuthorArea" asp-controller="BlogPosts">Author Area</a>
                <a class="mx-3 axil-button button-rounded btn btn-success mb-5" asp-action="BlogFilter" asp-controller="BlogPosts" asp-route-filter="Drafts">Drafts</a>

            }
            else
            {
                <a class="mx-3 axil-button button-rounded btn btn-success mb-5" asp-action="BlogFilter" asp-controller="BlogPosts" asp-route-filter="Drafts">Drafts</a>
                <a class="mx-3 axil-button button-rounded btn btn-success mb-5" asp-action="BlogFilter" asp-controller="BlogPosts" asp-route-filter="Deleted">Deleted</a>

            }
        </div>


        <!-- Start Post List  -->
        @* BEGIN: show this for each post *@
        @foreach (BlogPost blogPost in Model)
        {

            <div class="row my-3">
                <div class="col-lg-8 col-xl-8">
                    <div class="content-block post-list-view mt--30">
                        <div class="post-thumbnail">
                            <a asp-action="Details" asp-controller="BlogPosts" asp-route-slug="@blogPost.Slug">
                                <img src="@_ImageService.ConvertByteArrayToFile(blogPost.ImageData,blogPost.ImageType,DefaultImage.BlogPostImage)" alt="Post Image">
                            </a>
                        </div>
                        <div class="post-content">
                            <div class="post-cat">
                                <div class="post-cat-list">
                                    <h6>
                                        <span class="">
                                            <span data-text="@blogPost.Category?.Name">@blogPost.Category?.Name</span> @* post category *@
                                        </span>
                                    </h6>
                                </div>
                            </div>
                            <h4 class="title"><a asp-action="Details" asp-controller="BlogPosts" asp-route-slug="@blogPost.Slug">@blogPost.Title</a></h4>
                            <div class="post-meta-wrapper">
                                <div class="post-meta">
                                    <div class="content">
                                        <ul class="post-meta-list">
                                            <li>@blogPost.Created.ToString("MMM dd, yyyy")</li>
                                            <li>Comments: @blogPost.Comments.Count</li>
                                        </ul>
                                    </div>
                                </div>
                                <ul class="social-share-transparent justify-content-end fw-bold">
                                    @* BLOG STATUS: show just one of these! *@
                                    @if (blogPost.IsPublished == true && blogPost.IsDeleted == false)
                                    {
                                        <li><a class="text-success">Published</a></li>
                                    }
                                    else if (blogPost.IsDeleted == true)
                                    {
                                        <li><a class="text-danger">Deleted</a></li>
                                    }
                                    else
                                    {
                                        <li><a class="text-warning">Unpublished</a></li>
                                    }
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-xl-4">
                    <div class="content-block post-list-view mt--30 h-100">
                        <div class="post-content d-flex flex-column gap-3 align-items-center">
                            @if (blogPost.IsPublished == false)
                            {
                                <a class="w-75 btn btn-outline-success"
                                   asp-action="Publish" asp-controller="BlogPosts" asp-route-id="@blogPost.Id">Publish</a>
                            }
                            else
                            {
                                <a class="w-75 btn btn-outline-success"
                                   asp-action="Unpublish" asp-controller="BlogPosts" asp-route-id="@blogPost.Id">Unpublish</a>
                            }
                            <a class="w-75 btn btn-outline-warning"
                               asp-action="Edit"
                               asp-controller="BlogPosts"
                               asp-route-id="@blogPost.Id">
                                Edit
                            </a>
                            @if (blogPost.IsDeleted == false)
                            {
                                <a class="w-75 btn btn-outline-danger"
                                   asp-action="Delete" asp-controller="BlogPosts" asp-route-id="@blogPost.Id">Delete</a>
                            }
                            else
                            {
                                <a class="w-75 btn btn-outline-danger"
                                   asp-action="Undelete" asp-controller="BlogPosts" asp-route-id="@blogPost.Id">Undelete</a>
                            }

                        </div>
                    </div>
                </div>
            </div>

        }
        @* END: show this for each post *@


        @* paginated navigation *@
        <div>
            <div>
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
            </div>
            @Html.PagedListPager(Model, pageNum => Url.Action(actionName, new { pageNum, filter}),
            new PagedListRenderOptions
            {
            LiElementClasses = new string[] {"my-page-item"},
            PageClasses = new string[] {"my-page-link" }
            })
        </div>
        <!-- End Post List  -->
    </div>
</div>
<!-- End Post List Wrapper  -->

Views/BlogPosts/Create.cshtml
@model OnTheBlog.Models.BlogPost
@inject IImageService _imageService
@inject IBlogService _blogService

@{
    ViewData["Title"] = "Create";
}

<style>
    .ck-editor__editable_inline {
        min-height: 600px;
    }

    input.largerCheckbox {
        width: 30px;
        height: 30px;
    }

    label.form-check-label {
        font-size: 22px;
    }
</style>

<div class="post-single-wrapper axil-section-gap bg-color-white">
    <div class="container">
        <h1>Create</h1>
        <h4>BlogPost</h4>
    </div>
    <hr />
    <main class="container mt-5">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-12 col-lg-4">
                    <div class="form-group">
                        <label asp-for="ImageFile" class="control-label">Blog Post Image</label>
                        <img class="img-fluid border rounded-3 mb-2" style="max-height: 350px;" src="@_imageService.ConvertByteArrayToFile(Model?.ImageData!,Model?.ImageType!,DefaultImage.BlogPostImage)" id="blogImage">
                        <input asp-for="ImageFile" type="file" class="form-control mt-3 pt-2" accept=".png,.jpg,.jpeg,.gif"
                               onchange="document.getElementById('blogImage').src = window.URL.createObjectURL(this.files[0])" />
                    </div>
                    <div class="form-group">
                        <label asp-for="Title" class="control-label"></label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Abstract" class="control-label"></label>
                        <textarea asp-for="Abstract" class="form-control" rows="1"></textarea>
                        <span asp-validation-for="Abstract" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CategoryId" class="control-label">Category</label>
                        <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                    </div>
                </div>
                <div class="col-12 col-lg-8">
                    <div class="form-group">
                        <label asp-for="Content" class="control-label"></label>
                        <textarea asp-for="Content" class="editor form-control"></textarea>
                        <span asp-validation-for="Content" class="text-danger"></span>
                    </div>
                    <div class="form-group" id="tagContainer">
                        <label asp-for="Tags"></label>

                        <input class="form-control" type="text" id="tagInput" name="StringTags" autocomplete="off" />

                        <div class="tagcloud axil-single-widget mt-2" style="display: none;">
                            <!-- tags go here -->
                            @foreach (Tag tag in await _blogService.GetTagsAsync())
                            {
                                <a role="button">@tag.Name</a>
                            }
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group d-flex justify-content-end">
                <label class="form-check-label me-4 mt-2" asp-for="IsPublished">Publish?</label>
                <input class="largerCheckbox me-8" type="checkbox" asp-for="IsPublished" />
                <span asp-validation-for="IsPublished" class="text-danger"></span>
            </div>
            <div class="form-group d-flex justify-content-end">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
        <div class="form-group mt-5 start-0">
            <a asp-controller="BlogPosts" asp-action="AuthorArea">Back</a>
        </div>
    </main>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <!--CK Editor-->
    <script src="https://cdn.ckeditor.com/ckeditor5/37.1.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('.editor'), {
                licenseKey: '',
            })
            .then(editor => {
                window.editor = editor;
            });
    </script>

    <script>
        // override the jQuery ":contains" selector to make it case insensitive
        jQuery.expr[':'].contains = function (a, i, m) {
            return $(a).text().toUpperCase()
                .indexOf(m[3].toUpperCase()) >= 0;
        };

        $(document).ready(function () {

            //add an event listener on the tag input to show the tagcloud
            $('#tagInput').focus(function () {
                $('.tagcloud').show(300);
            });
            // add an event listener to Hide the tagcloud when I'm not on the tag input
            $('form *:not("#tagInput")').focus(function () {
                if ($('.tagcloud').is(':visible')) {
                    $('.tagcloud').hide(300);
                }
            });

            $('#tagInput').keyup(function () {

                // get just the text from the input after the last comma
                let inputTags = $(this).val().split(',');

                //remove the last element of inputTags and trim any whitespace
                let searchString = inputTags.pop().trim();

                // hide all the tags which do not contain that text
                $('.tagcloud > a:not( :contains(' + searchString + ') )').hide();

                // show all the tags which do contain that text
                $('.tagcloud > a:contains(' + searchString + ')').show();

                $('.disabledTag').removeClass('disabledTag');

                inputTags.forEach(tag => {
                    if (tag.trim() == '') {
                        return;
                    }
                    let matchingTags = $('.tagcloud > a:contains(' + tag.trim() + ')');

                    matchingTags.each(function () {

                        if ($(this).text().trim().toLowerCase() == tag.trim().toLowerCase()) {
                            $(this).addClass('disabledTag');
                        }

                    });


                });

            });

            $('.tagcloud > a').click(function () {
                //if it's disabled do nothing
                if ($(this).hasClass('disabledTag')) {
                    $('#tagInput').focus();
                    return;
                }

                //get name of tag clicked
                let tagName = $(this).text();

                //get currently in the tag input and split by commas
                let tags = $('#tagInput').val().split(',');

                //remove last search from input
                tags.pop();

                //replace with tag clicked
                tags.push(tagName);

                //change text in input
                let tagsAsString = tags.map(t => t.trim()).join(', ') + ', ';
                $('#tagInput').val(tagsAsString);
                $('#tagInput').focus();
                $('#tagInput').keyup();

            });

        });
    </script>
}

Views/BlogPosts/Delete.cshtml
@model OnTheBlog.Models.BlogPost

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BlogPost</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Abstract)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Abstract)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Updated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Updated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Slug)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Slug)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsPublished)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsPublished)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageData)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageData)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>